### ISSUE TITLE
請修正一個小地方

### ISSUE THREAD

**Issue by terry0201** [terry0201/Cam_Feild_Setting_UI#11]
![image](https://user-images.githubusercontent.com/39862983/141736671-591553d7-a630-408d-ba53-aa873cf96878.png)
如上圖338行，請將'attribute'改為'attributes'，以符合原始labelme的輸出格式
謝謝

**Comment by terry0201** [comment]
此處修改完，和上周的功能完成後，也請再push最新的exe

**Comment by love124356** [comment]
不好意思，沒有注意到有issue，目前已經修改完畢，open和save xml的地方都有修正為attributes，應該沒有問題，也發了新的request了。

**Comment by terry0201** [comment]
edit模式時，物件名稱沒有選單了
![image](https://user-images.githubusercontent.com/39862983/144212719-73b88984-f654-4bb2-8152-cb010943acdd.png)

**Comment by terry0201** [comment]
需要，麻煩加進去了，謝謝

**Comment by love124356** [comment]
好的~ 那我晚點會再發一次request
